import '../models/vault_item.dart';

/// The outcome of comparing one locally-dirty item's edit against the
/// remote state found for the same id during a sync (plan §4 step 4).
enum MergeOutcome {
  /// No remote change since the local edit's base version: the local edit
  /// simply supersedes it, push as-is.
  fastForwardLocal,

  /// Remote changed concurrently: keep both. The local edit is cloned to a
  /// new item id as a "conflicted copy"; the original id keeps the remote
  /// version.
  conflict,
}

class MergeResult {
  const MergeResult({required this.outcome, this.conflictCopy});

  final MergeOutcome outcome;

  /// Populated only when [outcome] is [MergeOutcome.conflict].
  final VaultItem? conflictCopy;
}

/// Decides how to merge one locally-dirty [local] edit (which started from
/// [localBaseVersion], i.e. the item's version at the time the local device
/// last saw it) against a [remote] item found at the same id whose content
/// actually changed since our last sync.
///
/// Deliberately never silently drops data: a real concurrent edit always
/// produces a conflict copy rather than a field-level merge, since vault
/// items are opaque secrets that can't be merged meaningfully (plan §4).
/// [conflictItemId] should be a fresh id (e.g. a new uuid) generated by the
/// caller.
MergeResult resolveItemConflict({
  required VaultItem local,
  required int localBaseVersion,
  required VaultItem remote,
  required String conflictItemId,
  required String localDeviceId,
  required DateTime now,
}) {
  if (remote.version <= localBaseVersion) {
    // Remote's change is the one our edit was already based on (or older);
    // nothing concurrent happened, so our edit simply supersedes it.
    return const MergeResult(outcome: MergeOutcome.fastForwardLocal);
  }

  final conflictCopy = local.copyWith(
    id: conflictItemId,
    version: 1,
    updatedAt: now,
    updatedByDevice: localDeviceId,
    deleted: false,
    data: relabelForConflict(local.data, localDeviceId, now),
  );
  return MergeResult(outcome: MergeOutcome.conflict, conflictCopy: conflictCopy);
}

/// Appends a human-readable "(conflicted copy from ...)" marker to whichever
/// field a user would actually see in the vault list, so a conflict copy is
/// distinguishable at a glance rather than only by id.
VaultItemData relabelForConflict(VaultItemData data, String deviceId, DateTime at) {
  final suffix = ' (conflicted copy from $deviceId at ${at.toIso8601String()})';
  return switch (data) {
    PasswordItemData d => d.copyWith(name: '${d.name}$suffix'),
    PasskeyItemData d => d.copyWith(rpName: '${d.rpName}$suffix'),
  };
}
